// <copyright file="AtisVoiceMeta.cs" company="Justin Shannon">
// Copyright (c) Justin Shannon. All rights reserved.
// Licensed under the GPLv3 license. See LICENSE file in the project root for full license information.
// </copyright>

using System.Text.Json.Serialization;

namespace Vatsim.Vatis.Profiles.Models;

/// <summary>
/// Represents metadata related to the ATIS voice configuration.
/// </summary>
public class AtisVoiceMeta
{
    /// <summary>
    /// Gets or sets a value indicating whether text-to-speech should be used for ATIS voice configuration.
    /// </summary>
    public bool UseTextToSpeech { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether the voice ATIS is stitched from pre-recorded WAV clips.
    /// Mutually exclusive with <see cref="UseTextToSpeech"/>.
    /// </summary>
    public bool UseWavPack { get; set; }

    /// <summary>
    /// Gets or sets the id of the voice pack, from vATIS's voice pack library, that the station uses.
    /// </summary>
    public string? WavPackId { get; set; }

    /// <summary>
    /// Gets or sets the folder of a voice pack configured by path before the voice pack library existed.
    /// </summary>
    public string? WavPackPath { get; set; }

    /// <summary>
    /// Gets a value indicating whether the voice ATIS is generated by vATIS (text-to-speech or WAV pack)
    /// rather than recorded by the user.
    /// </summary>
    [JsonIgnore]
    public bool IsAutomatic => UseTextToSpeech || UseWavPack;

    /// <summary>
    /// Gets or sets the name of the voice to be used for ATIS voice configuration.
    /// </summary>
    public string? Voice { get; set; } = "Default";

    /// <summary>
    /// Gets or sets the speech rate multiplier.
    /// </summary>
    public int SpeechRate { get; set; } = 180;

    /// <summary>
    /// Creates a new instance of <see cref="AtisVoiceMeta"/> that is a copy of the current instance.
    /// </summary>
    /// <returns>A new <see cref="AtisVoiceMeta"/> instance that is a copy of this instance.</returns>
    public AtisVoiceMeta Clone()
    {
        return new AtisVoiceMeta
        {
            UseTextToSpeech = UseTextToSpeech,
            UseWavPack = UseWavPack,
            WavPackId = WavPackId,
            WavPackPath = WavPackPath,
            Voice = Voice,
            SpeechRate = SpeechRate
        };
    }
}
