// <copyright file="AtisBuilderResponse.cs" company="Justin Shannon">
// Copyright (c) Justin Shannon. All rights reserved.
// Licensed under the GPLv3 license. See LICENSE file in the project root for full license information.
// </copyright>

namespace Vatsim.Vatis.Atis;

/// <summary>
/// Represents the response generated by an ATIS builder, containing textual ATIS, spoken ATIS, and audio data.
/// </summary>
/// <param name="TextAtis">The textual ATIS response.</param>
/// <param name="SpokenText">The spoken ATIS response.</param>
/// <param name="AudioBytes">The audio data for the ATIS response.</param>
public record AtisBuilderResponse(string? TextAtis, string? SpokenText, byte[]? AudioBytes);
