set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR arm64)

set(CMAKE_C_COMPILER oa64-clang)
set(CMAKE_CXX_COMPILER oa64-clang++)

set(CMAKE_AR /cctools/bin/arm64-apple-darwin24-ar)
set(CMAKE_RANLIB /cctools/bin/arm64-apple-darwin24-ranlib)
set(CMAKE_LIBTOOL /cctools/bin/arm64-apple-darwin24-libtool)

set(CMAKE_OSX_ARCHITECTURES arm64)
set(CMAKE_OSX_DEPLOYMENT_TARGET "12.0")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_SYSROOT /osxcross/SDK/MacOSX15.0.sdk)
set(CMAKE_FIND_ROOT_PATH /osxcross/SDK/MacOSX15.0.sdk)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
